# Generated by Django 6.0.3 on 2026-03-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='ID Enseignant')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('gender', models.CharField(choices=[('Male', 'Masculin'), ('Female', 'Féminin')], max_length=10, verbose_name='Genre')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('joining_date', models.DateField(verbose_name="Date d'embauche")),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Numéro de téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('experience', models.CharField(blank=True, max_length=50, null=True, verbose_name='Expérience')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Photo de profil')),
            ],
        ),
    ]
