# Generated by Django 6.0.3 on 2026-03-31 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du département')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('head_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='faculty.teacher', verbose_name='Responsable (Enseignant)')),
                ('teachers', models.ManyToManyField(blank=True, related_name='departments', to='faculty.teacher', verbose_name='Enseignants')),
            ],
        ),
    ]
