# Generated by Django 6.0.3 on 2026-04-01 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_holiday'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100, verbose_name="Nom de l'examen (ex: Contrôle Continu 1)")),
                ('exam_date', models.DateField(verbose_name="Date de l'examen")),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subject', verbose_name='Matière')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note obtenue')),
                ('total_marks', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Note sur (ex: 20)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Appréciation')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.exam', verbose_name='Examen')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Étudiant')),
            ],
        ),
    ]
