# Generated by Django 6.0.3 on 2026-04-01 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_exam_examresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')], verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Salle')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.teacher', verbose_name='Enseignant')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
