# Generated by Django 6.0.3 on 2026-03-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='lmmwSunZqVmXU2eG7TSwyRBI42xfCiNk', editable=False, max_length=32, unique=True),
        ),
    ]
