# Generated by Django 6.0.3 on 2026-04-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='rUehSIpgYq1YObEmhuP44HGVDvpo8Ysa', editable=False, max_length=32, unique=True),
        ),
    ]
