# Generated by Django 6.0.3 on 2026-04-01 14:25

import home_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default=home_auth.models.generate_token, editable=False, max_length=32, unique=True),
        ),
    ]
